name: webdeploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
  

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        
      - name: 📂 Sync files
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          remote: /home/poslam/web-susch/
          local: /home/runner/work/web-susch
      
      - name: 🚀 Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd /home/poslam/web-susch
            docker compose up --build -d